name: Publish Docker image and Visual Studio Code extension

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Select release version
        id: version
        run: printf 'tag=1.%(%Y%m%d)T.%(%H%M)T' >> $GITHUB_OUTPUT

      - uses: actions/checkout@v2

      - run: npm install -g vsce
      - run: npm install
      - run: npm run package
      - run: |
          cd dist
          sed -i -e 's|0.0.0|${{ steps.version.outputs.tag }}|g' package.json
          vsce package --no-dependencies
          vsce publish --no-dependencies -p ${{ secrets.VSCE_TOKEN }}
